name: rhiprofile

on:
  workflow_dispatch:

env:
  UTILS: /tmp/572ab980b73e2520cd2dc96165d36c90

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set library
        run: |
          sudo apt-get update
          sudo apt-get install -y libxxhash-dev libcrypto++-dev libglib2.0-dev
          (
            mkdir -p ${{ env.UTILS }}
            cd ${{ env.UTILS }}
            git clone https://github.com/reshifr/rhi.git
            cd rhi
            make dynamic
          )
      - name: Benchmark
        run: |
          chmod +x rhiprofile.sh
          bash -x rhiprofile.sh
